# mainly used for development

services:
  ide:
    build: 
      context: ./apps/ide
    image: ide
  environment:
    build:
      context: ./containers/environments/${ENVIRONMENT:-python}
      additional_contexts:
        ide: service:ide
    environment:
      - PROJECT_ID=development-project
      - STARTER_ZIP_URL=${STARTER_ZIP_URL:-}
      - PROJECT_OVERVIEW=${PROJECT_OVERVIEW:-# Project Overview\nThis is a simple outline. `inline code blocks`, **bold text**, and _italic text_ are supported.\n\n## Features\n- Feature 1\n- Feature 2\n\n## Getting Started\n1. Step one\n2. Step two}
      - DUE_AT=${DUE_AT:-1825400106}
      - VSX_REGISTRY_URL=${VSX_REGISTRY_URL:-http://127.0.0.1:0}
    volumes:
      # - efs-mount:/mnt/efs/
      - ./.mnt/efs/:/mnt/efs/
  reverse-proxy:
    build:
      context: ./containers/reverse-proxy
    environment:
      - SESSION_SECRET=${PASSWORD:-password}
      - UPSTREAM_TARGET=environment:3000
    ports:
      - 8080:80
  watchdog:
    build:
      context: ./containers/watchdog
    environment:
      - PROJECT_ID=development-project
      - MAX_SESSION_SECONDS=${MAX_SESSION_SECONDS:-3600}
      - MAX_SIZE_MB=${MAX_SIZE_MB:-2000}
    volumes:
      # - efs-mount:/mnt/efs/
      - ./.mnt/efs/:/mnt/efs/
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
  minio:
    image: minio/minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      mc alias set local http://minio:9000 admin password123;
      mc mb local/student-assignments-bucket || true;
      exit 0;
      "
volumes:
  pgdata:
  efs-mount:
  minio_data: