import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import { Providers } from "./providers";
import "./globals.css";

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
});

const satoshi = localFont({
	src: "../public/fonts/Satoshi-Variable.woff2",
	variable: "--font-satoshi",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${inter.variable} ${satoshi.variable} h-full antialiased`}
		>
			<body className="min-h-full flex flex-col font-satoshi">
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
